# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Zhe Zhao
description: >- # this means to ignore newlines until "baseurl:"
  This is the personal website of Zhe Zhao
baseurl: "/ZheZhao" # the subpath of the site
url: "https://zzhaozhe-profolio.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: CV
    - name: Publication

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: zzhaozhe@umich.edu
      link: mailto:zzhaozhe@umich.edu
  follow:
    - name: LinkedIn
      link: https://linkedin.com/in/zhe-zhao-67088910b
    - name: GitHub
      link: https://github.com/zzhaozhe-profolio

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
